### ISSUE TITLE
GLSL Version for OpenGL based players (i.e. mpv) and Linux

### ISSUE THREAD

**Issue by Waiifu** [bloc97/Anime4K#1]
Hey,

I think it would be nice to have GLSL versions of this, especially since as far as I'm aware, a large portion of the more video-tweaky community often use's Linux and OpenGL based players like mpv, rather than DirectX.

**Comment by Nalapl3** [comment]
People who are actually knowledgable about video to the point they care about custom shaders wouldn't ever use this. It's really not as good as the author claims, in fact it looks quite awful when you zoom in.

**Comment by bloc97** [comment]
@Nalapl3 This algorithm performs best for 1080p -> 2160p anime upscaling. Other resolutions are not as good. If you find failure cases as you claim, please create a new issue so we can compile all the failure cases and sort them out.

**Comment by Nalapl3** [comment]
I just checked some of the screenshots in your results folder. How can you say this looks good?
https://files.catbox.moe/cdt9f1.png
https://files.catbox.moe/lus9dc.png

**Comment by bloc97** [comment]
State of the art for video. People do not stare at the corner of a screen looking for aliasing when watching anime. The general perceptual quality is noticeably better with this on than off (at least on 4K displays). As said in the readme we suggest the reader to try it themselves before coming to a conclusion instead of only watching the comparison files.

**Comment by Nalapl3** [comment]
No, it's not state of the art for video. It has been implemented before. And it only seems better if you don't pay any attention at all, or if you're a fan of oversharpened video that's washed out of all details.

**Comment by bloc97** [comment]
Perceptual quality is subjective. Since this algorithm will never be used for transcodes you can just turn it off.

**Comment by Nalapl3** [comment]
I sure hope it won't. I wouldn't really be surprised, people do a lot of terrible things with their encodes.

**Comment by bloc97** [comment]
GLSL Shaders implemented, closing issue.
