### ISSUE TITLE
Can filters be used for Encoding?

### ISSUE THREAD

**Issue by Blub86** [bloc97/Anime4K#103]
Hallo,
Can your filters be used while encoding video? Is there any Software that can use your glsl-filters and apply them in the encoding process?
Asking because I have a HTPC in my living room with only an Intel GPU that is to weak to play files with shaders enabled.
I tied to use mpv to encode a video on my ubuntu-machine with the following:

> mpv input.mkv --vf=gpu="w=1280:h=720" --glsl-shaders="/shaders/Anime4K_Upscale_CNN_L_x2_Denoise.glsl:/shaders/Anime4K_Auto_Downscale_Pre_x4.glsl:/shaders/Anime4K_Deblur_DoG.glsl:/shaders/Anime4K_DarkLines_HQ.glsl:/shaders/Anime4K_ThinLines_HQ.glsl:/shaders/Anime4K_Upscale_CNN_M_x2_Deblur.glsl"--o=output.mkv

The result does not look as good as the original file in mpv with shaders enabled.

Is there a way to properly apply + reencode a video-file with your shaders? If I would need another Program or Windows instead of Linux that’s also fine by me.
THX for your help ;)

**Comment by Blub86** [comment]
I am closing the issue, found solution:

Need to set a Constant Rate Factor with `--ovcopts=crf=VALUE` and need to set higher resolution --> 720p to 1080p.
Also need to set `--vf=format=yuv420p` for working hw-decoding.

**Comment by lsl330** [comment]
> 

i have the same problem,please help!!

**Comment by feanor3** [comment]
I have installed Ubuntu on an hard drive and it worked on it
