### ISSUE TITLE
How does the method compare to Anisotropic diffusion or Total variation denoising?

### ISSUE THREAD

**Issue by woctezuma** [bloc97/Anime4K#11]
How does the method compare to [Anisotropic diffusion](https://en.wikipedia.org/wiki/Anisotropic_diffusion) or [Total variation denoising](https://en.wikipedia.org/wiki/Total_variation_denoising)? Are there similarities in the approach?

**Comment by bloc97** [comment]
The technique is similar, but the objective function is different, they are minimizing ((Denoised Image - Noisy Image) + Laplacian of Denoised Image), while we are simply maximizing the gradient using a different kernel than the standard Discrete Laplacian operator.
