### ISSUE TITLE
Is it possible to set an upscale resolution?

### ISSUE THREAD

**Issue by RandomAccountt** [bloc97/Anime4K#113]
When running mpv with a 480p anime on my lower resolution display (1920\*1080), upscaling is performed well. However, moving the mpv window over to my higher resolution display (2560*1440), the video constantly stutters and is unwatchable. I assume this is because upscaling from 480p to 1440p is too demanding (although I'm still unsure if this is the cause). Is there a way to limit the upscale to 1080p?

**Comment by hooke007** [comment]
Most of the aiupscalers only make 2x once a time.
