### ISSUE TITLE
Can I use DTD shader together with darklines?

### ISSUE THREAD

**Issue by wolfdaddyh** [bloc97/Anime4K#123]
Hi, based on the wiki, DTD shader is basically upscale and darklines + thinlines + deblur but mpv doesn’t like using the same shader twice so I’m wondering if it’s okay to use dtd shader together with dark and thinlines.

**Comment by hooke007** [comment]
Of course you can.

>but mpv doesn’t like using the same shader twice

why and what do you mean `like`?
No problem here using the same shader twice.
![Snipaste_2021-06-21_18-30-59](https://user-images.githubusercontent.com/41094733/122748557-eacf3780-d2be-11eb-86f7-f2b733cf03e2.jpg)

**Comment by hooke007** [comment]
@bloc97 [wiki's ins](https://github.com/bloc97/Anime4K/wiki/Upscale-Shaders#special-considerations) is outdated and I cannot reproduce the issue you mentioned. Maybe update it ?
