### ISSUE TITLE
What shaders were used on example pic?

### ISSUE THREAD

**Issue by 4zjata** [bloc97/Anime4K#124]
im talking about this one

[
![image](https://user-images.githubusercontent.com/63453921/123461516-7b708500-d5e9-11eb-8ab2-afcbcebeee26.png)
](url)

**Comment by bloc97** [comment]
It's a very old comparison and I don't remember which specific settings I used for the original Anime4K shader. It's just there for illustrative purposes and the default settings for the newer shaders perform better anyway.

**Comment by 4zjata** [comment]
which one do you think is best for old anime?
