### ISSUE TITLE
Mac

### ISSUE THREAD

**Issue by Hyper3557** [bloc97/Anime4K#129]
make anime4k work with macOS and also give us a detailed guide on how a normal person should use this.

**Comment by MikeAMags** [comment]
> make anime4k work with macOS and also give us a detailed guide on how a normal person should use this.

I was in the same boat, I am not a coder but know enough to be dangerous. I am running a MacBookPro16,1 (OS X 11.5.2).

First I downloaded a ZIP file from the <>Code page. It was located in my download folder. Unzip it (double click it) and a new folder appears "Anime4K-master". Open the folder and look for the file "GLSL_Instructions.md". Open it. I recommend using the application "Atom" text editor, but you can use whichever you like. In the "GLSL_Instructions.md" you will find in line 4, to download and install MPV player and in line 5, to download ".glsl shader files". Links provided in both of those rows.

Once you download the MPV file, you install it by following the instructions. Then, you COPY the ".glsl shader files" to where it tells you in the corresponding MPV folders.

Once you have MPV and the .glsl shaders installed, you might want to take a look at the "mpv.conf" file to configure your mpv player.

If you want to see the anime4k shaders work in real time, then you will also need to modify "input.conf".

Finally, launch a terminal session and type mpv and this happens:
 `
ip-xxx-xxx-xxx-xxx:~ my.name$ mpv
mpv 0.33.0-UNKNOWN Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
 built on Thu Aug  5 09:37:52 PDT 2021
FFmpeg library versions:
   libavutil       56.70.100
   libavcodec      58.134.100
   libavformat     58.76.100
   libswscale      5.9.100
   libavfilter     7.110.100
   libswresample   3.9.100
FFmpeg version: 4.4

Usage:   mpv [options] [url|path/]filename

Basic options:
 --start=<time>    seek to given (percent, seconds, or hh:mm:ss) position
 --no-audio        do not play sound
 --no-video        do not play video
 --fs              fullscreen playback
 --sub-file=<file> specify subtitle file to use
 --playlist=<file> specify playlist file

 --list-options    list all mpv options
 --h=<string>      print options which contain the given string in their name

ip-xxx-xxx-xxx-xxx:~ my.name$
`
In my case, I type "mpv my/file/to/playback.mp4

The only thing I haven't figured out is the CONTROL panel to show in the player.

If you have questions, I will help the best I can.

**Comment by Hyper3557** [comment]
> > make anime4k work with macOS and also give us a detailed guide on how a normal person should use this.
> 
> I was in the same boat, I am not a coder but know enough to be dangerous. I am running a MacBookPro16,1 (OS X 11.5.2).
> 
> First I downloaded a ZIP file from the <>Code page. It was located in my download folder. Unzip it (double click it) and a new folder appears "Anime4K-master". Open the folder and look for the file "GLSL_Instructions.md". Open it. I recommend using the application "Atom" text editor, but you can use whichever you like. In the "GLSL_Instructions.md" you will find in line 4, to download and install MPV player and in line 5, to download ".glsl shader files". Links provided in both of those rows.
> 
> Once you download the MPV file, you install it by following the instructions. Then, you COPY the ".glsl shader files" to where it tells you in the corresponding MPV folders.
> 
> Once you have MPV and the .glsl shaders installed, you might want to take a look at the "mpv.conf" file to configure your mpv player.
> 
> If you want to see the anime4k shaders work in real time, then you will also need to modify "input.conf".
> 
> Finally, launch a terminal session and type mpv and this happens:
> `
> ip-xxx-xxx-xxx-xxx:~ my.name$ mpv
> mpv 0.33.0-UNKNOWN Copyright © 2000-2020 mpv/MPlayer/mplayer2 projects
> built on Thu Aug 5 09:37:52 PDT 2021
> FFmpeg library versions:
> libavutil 56.70.100
> libavcodec 58.134.100
> libavformat 58.76.100
> libswscale 5.9.100
> libavfilter 7.110.100
> libswresample 3.9.100
> FFmpeg version: 4.4
> 
> Usage: mpv [options] [url|path/]filename
> 
> Basic options:
> --start= seek to given (percent, seconds, or hh:mm:ss) position
> --no-audio do not play sound
> --no-video do not play video
> --fs fullscreen playback
> --sub-file= specify subtitle file to use
> --playlist= specify playlist file
> 
> --list-options list all mpv options
> --h= print options which contain the given string in their name
> 
> ip-xxx-xxx-xxx-xxx:~ my.name$
> `
> In my case, I type "mpv my/file/to/playback.mp4
> 
> The only thing I haven't figured out is the CONTROL panel to show in the player.
> 
> If you have questions, I will help the best I can.

OMG thank you soooo soo much for your help! You are the only person who truly understood me.

**Comment by hooke007** [comment]
It seems your problem is "HOW to use mpv"???
