### ISSUE TITLE
Shaders not being run on Arch Linux

### ISSUE THREAD

**Issue by afromanDAN** [bloc97/Anime4K#131]
**Describe the bug**
The shaders are not being run. I get this error:
`[input] Command change-list has trailing unused arguments: ': show-text "Anime4K: Mode A (Fast)"'.
[input] Command was defined at /home/dan/.config/mpv/input.conf:3.
[input] Invalid command for key binding 'Ctrl+4': 'no-osd change-list glsl-shaders set "~/.config/mpv/shaders/Anime4K_Clamp_Highlights.glsl:~/.config/mpv/shaders/Anime4K_Restore_CNN_M.glsl:~/.config/mpv/shaders/Anime4K_Upscale_CNN_x2_M.glsl:~/.config/mpv/shaders/Anime4K_AutoDownscalePre_x2.glsl:~/.config/mpv/shaders/Anime4K_AutoDownscalePre_x4.glsl:~/.config/mpv/shaders/Anime4K_Upscale_CNN_x2_S.glsl": show-text "Anime4K: Mode A (Fast)"'`

**To Reproduce**
1. set input.conf to `CTRL+4 no-osd change-list glsl-shaders set "~/.config/mpv/shaders/Anime4K_Clamp_Highlights.glsl:~/.config/mpv/shaders/Anime4K_Restore_CNN_M.glsl:~/.config/mpv/shaders/Anime4K_Upscale_CNN_x2_M.glsl:~/.config/mpv/shaders/Anime4K_AutoDownscalePre_x2.glsl:~/.config/mpv/shaders/Anime4K_AutoDownscalePre_x4.glsl:~/.config/mpv/shaders/Anime4K_Upscale_CNN_x2_S.glsl": show-text "Anime4K: Mode A (Fast)"`
2. run file in mpv
3. press ctrl+4
4. check if shaders are running via ctrl+i
5. See error in terminal

**Expected behavior**
It supposed to run the shaders.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Version: 5.13.13-arch1-1 
 - GPU: GTX 1070
 - Media Player and Version: MPV 0.33.0-335-gc2dec023b7
 - Browser: NA

**Additional context**
NA

**Comment by bloc97** [comment]
I think the ; outside the quotes shouldn't be changed to :
Let me know if this works:
`CTRL+4 no-osd change-list glsl-shaders set "~/.config/mpv/shaders/Anime4K_Clamp_Highlights.glsl:~/.config/mpv/shaders/Anime4K_Restore_CNN_M.glsl:~/.config/mpv/shaders/Anime4K_Upscale_CNN_x2_M.glsl:~/.config/mpv/shaders/Anime4K_AutoDownscalePre_x2.glsl:~/.config/mpv/shaders/Anime4K_AutoDownscalePre_x4.glsl:~/.config/mpv/shaders/Anime4K_Upscale_CNN_x2_S.glsl"; show-text "Anime4K: Mode A (Fast)"`

I might have to update the instructions to specify this...

**Comment by afromanDAN** [comment]
yee that seems to have done the trick!
