### ISSUE TITLE
Large CPU hit after 1200p resize

### ISSUE THREAD

**Issue by BlackPowerade** [bloc97/Anime4K#134]
## **Describe the bug**
Resizing the player window beyond ~1200h results in a massive CPU utilization spike with Anime4K enabled.

## **To Reproduce**
1. Load up 480p video
2. Enable Anime4K
3. Resize player beyond ~1200h

## **Expected behavior**
Non-massive performance hit

### Below Breakpoint:
![general information below breakpoint](https://user-images.githubusercontent.com/21957509/134826982-66d37e08-589f-4342-a618-799135b687c8.png)
![Shaders below breakpoint](https://user-images.githubusercontent.com/21957509/134827000-5522371a-fccc-48ff-ad86-76389fb7adc5.png)
![system stats below breakpoint](https://user-images.githubusercontent.com/21957509/134827005-63f8bdcd-f914-427c-9f02-3c2029938c95.png)
### Above Breakpoint:
![general information above breakpoint](https://user-images.githubusercontent.com/21957509/134827013-34e1114c-7202-4761-89d5-14ed99e0a45a.png)
![shaders beyond breakpoint](https://user-images.githubusercontent.com/21957509/134827019-6bfb405d-e387-4417-b82d-6ef546923fc4.png)
![system stats above breakpoint](https://user-images.githubusercontent.com/21957509/134827027-e484fb13-b9ca-47b5-bcd2-57c854638471.png)

## **Desktop:**
 - OS: Windows 10 Enterprise 21H1, 19043
 - Version: 4.0.1 Stable
 - GPU: RTX 2070 Super
 - Media Player and Version: mpv 0.33.0-107-gdd86f195a6
 - Browser: Edge 94.0.992.31

## **Additional context**
From what I can tell this appears to be a copyback issue, as switching from nvdec-copy to nvdec significantly alleviated the problem. Not enough to fix it, still too much frame dropping.
This issue is present on all renderers, with the same similar results where the non-copy version performs much better.
I am not entirely sure where the breakpoint is, I could not get mpv to tell me the current window size. Best I can surmise is somewhere upwards of 1180ish.
This looks like it may be related to https://github.com/mpv-player/mpv/issues/8613 and https://github.com/bloc97/Anime4K/issues/119

Current mpv.conf is as follows:
```
input-default-bindings = no
input-ar-delay = 500
input-ar-rate = 20
keep-open = yes
keep-open-pause = no
osd-duration = 2000
script-opts = osc-scalewindowed=1.5,osc-hidetimeout=2000,console-scale=1
screenshot-directory = '~~desktop/'
hwdec = nvdec-copy
# Editor
scale = spline36
screenshot-format = png
save-position-on-quit = yes
cscale = spline36
dscale = spline36
osd-playing-msg = '${display-width}'

[protocol.https]
osd-playing-msg = '${media-title}'
```

**Comment by bloc97** [comment]
The mpv version might be too old. The latest Anime4K shaders will not work for versions previous to this update: https://github.com/mpv-player/mpv/commit/474ee003eddd278d871e7c1c760091b739880e8f

Try the latest nightly windows builds, they should not have this issue anymore.

**Comment by BlackPowerade** [comment]
Yep, that fixed it.
Thanks for the quick response.
