### ISSUE TITLE
Stolen work from you!

### ISSUE THREAD

**Issue by G-Rowell** [bloc97/Anime4K#135]
Hi,

your repo here,

Has been stolen & re-uploaded by the GitHub user: https://github.com/5R33CH4

Here is their repo in which they've stolen your work, and attributed it to themselves: https://github.com/5R33CH4/Anime4K-

They also have a GitHub org, where they likely also have some stolen work: https://github.com/tesseract-org.

Checkout their all their personal repos...

I'm sorry to bring you this bad news, this user has stolen >50 repos so you should consider reporting them to GitHub.

Galen

**Comment by bloc97** [comment]
Thanks for the report, currently it looks like their repo was removed.
