### ISSUE TITLE
[Question] Anime4K auto change shader based on resolution

### ISSUE THREAD

**Issue by Yuki-Soul** [bloc97/Anime4K#143]
Is there anyway to change shader based on screen resolution?

**Comment by mhtvsSFrpHdE** [comment]
Hi, I made a mpv Lua script to enable Anime4K depending on video resolution, check it out!

https://github.com/mhtvsSFrpHdE/AnimeAnyK-mpv

**Comment by Yuki-Soul** [comment]
> Hi, I made a mpv Lua script to enable Anime4K depending on video resolution, check it out!
> 
> https://github.com/mhtvsSFrpHdE/AnimeAnyK-mpv
Looks Great, I will try it.
