### ISSUE TITLE
[Question] AutoDownscalePre purpose

### ISSUE THREAD

**Issue by Katzenwerfer** [bloc97/Anime4K#154]
What exactly does the AutoDownscalePre shaders do?
Do they downscale the image in any set resolution? (even if the viewport res is native to the media)
Is it comparable to SSimDownscaler in any way?

**Comment by hooke007** [comment]
just a simple way to avoid the final upscaling beyond the target res.

**Comment by bloc97** [comment]
For `AutoDownscalePre_x4`, it downscales the image to half the screen resolution if necessary (resolution after upscaling is larger).
For `AutoDownscalePre_x2`, it downscales the image to the screen resolution if necessary.

**Comment by Katzenwerfer** [comment]
So if I understand correctly, those would only apply if those conditions are met, respectively

**Comment by bloc97** [comment]
Yes, and they only downscale to either half the screen resolution or to the screen resolution when the condition is met. Most of the time, those two shaders do nothing, but for example, 720p on a 4K screen would go like this:
`720p -> x2 upscale -> 1440p -> AutoDownscalePre_x4 -> 1080p -> x2 upscale -> 2160p`

Without AutoDownscalePre_x4, it would be:
`720p -> x2 upscale -> 1440p -> x2 upscale -> 2880p -> mpv downscale -> 2160p`

Most GPUs would not be able to handle 1440p -> 2880p upscaling, and if you put shaders after upscaling, working on 2880p images (5120x2880) is 1.7x slower than 4K (3840x2160) and has almost no benefit in visual quality when viewed from a reasonable distance.

**Comment by 088uiop** [comment]
After testing I found that:
The following H_in and H_out refer to the input height and final output height respectively
When 1.2 < H_out/H_in < 2, then AutoDownscalePre_x2 works (scale input resolution to output resolution)
When H_out/H_in >2.4, then AutoDownscalePre_x4 works (scale input resolution to half of output resolution)
It should be because when H_out/H_in > 1.2, Upscale_x2 works

**Comment by yooooooLeon** [comment]
您的邮件已收到！谢谢！
