### ISSUE TITLE
4.0.1 Release, but asset zip is 4.0

### ISSUE THREAD

**Issue by mhtvsSFrpHdE** [bloc97/Anime4K#155]
**Describe the bug**
This is release link of 4.0.1:  
https://github.com/bloc97/Anime4K/releases/tag/v4.0.1

The assets area have a zip file called `Anime4K_v4.0.zip`  
This zip file got SHA256 `139CD282086457C5ADC79CAF7B75B8B825091D71C9B54958C18745FEA62D7ED7`  
It's a same file to early 4.0 version, not new 4.1.

**To Reproduce**
1. Go to 'https://github.com/bloc97/Anime4K/releases/tag/v4.0.1'
2. Click on 'Anime4K_v4.0.zip'

**Expected behavior**
Release archive for 4.0.1 version.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: e.g. Windows 10
 - Version v4.0.1
 - GPU e.g. GTX 1080
 - Media Player and Version e.g. MPV
 - Browser e.g. chrome

**Additional context**

**Comment by mhtvsSFrpHdE** [comment]
As a workaround, download the `Source code (zip)` one,  
then unpack every file from glsl folder to mpv shader folder.

There are many folders, enter each one and unpack all subfolder content together to shader folder.

**Comment by bloc97** [comment]
v4.0.1 is not the same as the upcoming v4.1.0. Are you referring to the v4.0 release candidate?

**Comment by mhtvsSFrpHdE** [comment]
@bloc97 I should attach a screenshot, sorry for that

![image](https://user-images.githubusercontent.com/10773245/150451774-b79999ac-0fd8-468f-9ad9-3bdb5ef93a7b.png)

This zip is a 4.0 release zip

**Comment by bloc97** [comment]
Ah, it should be fine. I've just not bothered renaming all the shaders for minor versions eg. 4.0.x. If I'm not mistaken, they should be the same as the shaders found in this build https://github.com/bloc97/Anime4K/commit/4029bf701ecaa15f163cdc49cffe5501c1acf410 .

**Comment by mhtvsSFrpHdE** [comment]
@bloc97 Oh! I see, the zip file on my Download folder is already 4.0.1, but it named as 4.0.  
Thus, today when I check git update, I was thought I'm on 4.0 instead of 4.0.1.

True 4.0 zip is 756KB and 4.0.1 zip is 758KB. They are different.
