### ISSUE TITLE
How to customize what happens when I press Ctrl+1 ?

### ISSUE THREAD

**Issue by maheshn22** [bloc97/Anime4K#156]
In the docs, these are the instructions to activate shaders:
```
CTRL+1 no-osd change-list glsl-shaders set "~~/shaders/Anime4K_Clamp_Highlights.glsl;~~/shaders/Anime4K_Restore_CNN_VL.glsl;~~/shaders/Anime4K_Upscale_CNN_x2_VL.glsl;~~/shaders/Anime4K_AutoDownscalePre_x2.glsl;~~/shaders/Anime4K_AutoDownscalePre_x4.glsl;~~/shaders/Anime4K_Upscale_CNN_x2_M.glsl"; show-text "Anime4K: Mode A (HQ)"
```

How do I customize these, for eg: If I want to edit the shaders that get activated on pressing Ctrl+1, or if I want to edit the text that appears when I press Ctrl+1 ?
Which file is to be edited to achieve the above?

**Comment by larvanitis** [comment]
In the [`input.conf`](https://mpv.io/manual/stable/#input-conf)

Linux `~/.config/mpv/input.conf`
Windows `%APPDATA%\mpv\input.conf`

**Comment by maheshn22** [comment]
@larvanitis it worked! 
Thank you so much 😄
