### ISSUE TITLE
Upscale video from browser and not force full screen borderless

### ISSUE THREAD

**Issue by wilianwrech** [bloc97/Anime4K#159]
**Is your feature request related to a problem? Please describe.**
My feature request is not related to a problem.

**Describe the solution you'd like**
I just want better quality for videos played from the browser, but to this work, multiple things have to change.
1. The program must attach to browsers (or somehow, start its work)
2. Don't force fullscreen resolution for upscale. I believe the upscale resolution doesn't have to be directed linked with the monitor's resolution, it should have an option to choose how to upscale.
3. Don't force borderless, as this feature request is for watching videos on the browser, I don't think anyone would like to go borderless.
4. Viewport x video resolution, the user should be able to maximize or not the video and it should keep upscaling the selected resolution without interfering in the user viewport.

**Describe alternatives you've considered**
I don't know how difficult is to implement something like this, but I think it's not an easy thing to do. Something I always thought about is: Why it does not have an option to upscale the whole video output? Like the whole monitor output, despite the application. Example: I have a 1080p monitor, I want to upscale the whole content to 8k (upscale resolution) and still view it in 1080p (viewport resolution). I think this kind of approach serves a more generic use and is way easier to implement, but I am just speculating as I know nothing about it.

**Additional context**
-

**Comment by hooke007** [comment]
should be implemented by other softwares.
