### ISSUE TITLE
2 questions

### ISSUE THREAD

**Issue by splinter21** [bloc97/Anime4K#16]
1\
https://github.com/bloc97/Anime4K/blob/master/Java_Instructions.md
how do you get the default upsampling scale first, by bicubic? or bilinear?of other methods? And then use the enhancement Anime4K method.

2\
https://github.com/bloc97/Anime4K/blob/master/results/Graph.png?raw=true
how do you get the perceptual quality?

**Comment by stefnotch** [comment]
1
> the image can be upscaled in advance with any algorithm the user prefers 
> -- https://github.com/bloc97/Anime4K/blob/master/Preprint.md

2
https://github.com/bloc97/Anime4K/blob/master/Preprint.md#analysis

**Comment by bloc97** [comment]
More exactly, Mean Opinion Score from a dozen people comparing all the different algorithms, a few tests were to choose the best of 2, and a few were to rate all the algorithms from 0 to 10. The tests were double blind but we do know this is not rigorous enough to be considered a serious publication.

**Comment by splinter21** [comment]
@bloc97 how to set the Push_Strength and Push_Grad_Strength parameters when using?

**Comment by stefnotch** [comment]
> Available parameters:
> `java -jar Anime4K.jar [File_In] [File_Out] (Scale) (Push_Strength) (Push_Grad_Strength)`
is what the instructions say. What are you having troubles with?

**Comment by stefnotch** [comment]
@bloc97 Actually, am I overlooking something or is the documentation wrong about the order of the `(Push_Strength)` and `(Push_Grad_Strength)`

https://github.com/bloc97/Anime4K/blob/3d75fd642a7de50676f434a7fc8c5005c01399bf/java/src/main/java/com/bloc97/anime4k/Main.java#L45-L53

**Comment by splinter21** [comment]
I mean that I don't know what does these two parmeters mean, how to set these two parameters to make the output image better?

**Comment by bloc97** [comment]
@stefnotch You are right, they are wrong. I must have overlooked the change when writing the md.

**Comment by bloc97** [comment]
@splinter21 You can play around with the settings and see what they do, but to put it simply, Push_Stength thins black lines.  Push_Grad_Strength is the edge refinement strength. The higher it is, the sharper the edges. Put it too high and you lose texture detail.

**Comment by splinter21** [comment]
I know. Thanks！
