### ISSUE TITLE
Anime4K loads in, but shaders dont seem to apply[Linux 64-bit, Nvidia]

### ISSUE THREAD

**Issue by VihagChaturvedi** [bloc97/Anime4K#163]
**Describe the bug**
Upon following the installation guide mentioned in the wiki, I expected the video to improve it's quality, however, SHIFT+I doesn't show anything.

I have to also mention the fact that I have also replaced the ";" with ":"

Although, mpv does seem to recognize that I do have Anime4K, as the keybinds clearly work.

**To Reproduce**
Follow the instructions mentioned in wiki

**Expected behavior**
Expected the shaders to apply

**Screenshots**
Herein lie code blocks and screenshots

## mpv.conf
```
sub-auto=fuzzy
profile=gpu-hq
glsl-shaders="~~/shaders/Anime4K_Denoise_Bilateral_Mode.glsl:~~/shaders/Anime4K_Deblur_DoG.glsl:~~/shaders/Anime4K_DarkLines_HQ.glsl:~~/shaders/Anime4K_ThinLines_HQ.glsl:~~/shaders/Anime4K_Upscale_CNN_M_x2_Deblur.glsl"
```

## input.conf (This is extracted directly from the one in the wiki, with adjustments made for UNIX-based systems)
```
CTRL+1 no-osd change-list glsl-shaders set "~~/shaders/Anime4K_Clamp_Highlights.glsl:~~/shaders/Anime4K_Restore_CNN_M.glsl:~~/shaders/Anime4K_Upscale_CNN_x2_M.glsl:~~/shaders/Anime4K_AutoDownscalePre_x2.glsl:~~/shaders/Anime4K_AutoDownscalePre_x4.glsl:~~/shaders/Anime4K_Upscale_CNN_x2_S.glsl"; show-text "Anime4K: Mode A (Fast)"
CTRL+2 no-osd change-list glsl-shaders set "~~/shaders/Anime4K_Clamp_Highlights.glsl:~~/shaders/Anime4K_Restore_CNN_Soft_M.glsl:~~/shaders/Anime4K_Upscale_CNN_x2_M.glsl:~~/shaders/Anime4K_AutoDownscalePre_x2.glsl:~~/shaders/Anime4K_AutoDownscalePre_x4.glsl:~~/shaders/Anime4K_Upscale_CNN_x2_S.glsl"; show-text "Anime4K: Mode B (Fast)"
CTRL+3 no-osd change-list glsl-shaders set "~~/shaders/Anime4K_Clamp_Highlights.glsl:~~/shaders/Anime4K_Upscale_Denoise_CNN_x2_M.glsl:~~/shaders/Anime4K_AutoDownscalePre_x2.glsl:~~/shaders/Anime4K_AutoDownscalePre_x4.glsl:~~/shaders/Anime4K_Upscale_CNN_x2_S.glsl"; show-text "Anime4K: Mode C (Fast)"
CTRL+4 no-osd change-list glsl-shaders set "~~/shaders/Anime4K_Clamp_Highlights.glsl:~~/shaders/Anime4K_Restore_CNN_M.glsl:~~/shaders/Anime4K_Upscale_CNN_x2_M.glsl:~~/shaders/Anime4K_Restore_CNN_S.glsl:~~/shaders/Anime4K_AutoDownscalePre_x2.glsl:~~/shaders/Anime4K_AutoDownscalePre_x4.glsl:~~/shaders/Anime4K_Upscale_CNN_x2_S.glsl"; show-text "Anime4K: Mode A+A (Fast)"
CTRL+5 no-osd change-list glsl-shaders set "~~/shaders/Anime4K_Clamp_Highlights.glsl:~~/shaders/Anime4K_Restore_CNN_Soft_M.glsl:~~/shaders/Anime4K_Upscale_CNN_x2_M.glsl:~~/shaders/Anime4K_AutoDownscalePre_x2.glsl:~~/shaders/Anime4K_AutoDownscalePre_x4.glsl:~~/shaders/Anime4K_Restore_CNN_Soft_S.glsl:~~/shaders/Anime4K_Upscale_CNN_x2_S.glsl"; show-text "Anime4K: Mode B+B (Fast)"
CTRL+6 no-osd change-list glsl-shaders set "~~/shaders/Anime4K_Clamp_Highlights.glsl:~~/shaders/Anime4K_Upscale_Denoise_CNN_x2_M.glsl:~~/shaders/Anime4K_AutoDownscalePre_x2.glsl:~~/shaders/Anime4K_AutoDownscalePre_x4.glsl:~~/shaders/Anime4K_Restore_CNN_S.glsl:~~/shaders/Anime4K_Upscale_CNN_x2_S.glsl"; show-text "Anime4K: Mode C+A (Fast)"
CTRL+0 no-osd change-list glsl-shaders clr""; show-text "GLSL shaders cleared""
```
GLSL files in the `shaders` directory
![image](https://user-images.githubusercontent.com/45941793/154836609-694dcc8f-9feb-463e-a79c-4260b16f2270.png)

Output of `Shift+I 2` on mpv
![image](https://user-images.githubusercontent.com/45941793/154836690-ff4bf708-9784-462d-ae91-52422bc754e1.png)

**Desktop (please complete the following information):**
 - OS: Ultramarine Linux(Fedora based distribution) 64 Bit
 - Version: v4.0
 - GPU: Nvidia GTX 1650 
 - Driver version: 495.46(X11)
 - Media Player and Version: mpv 0.34.1
 - Browser: Not applicable

**Additional context**

**Comment by hooke007** [comment]
If your current `VO` doesn't support to show this page, then try another one (which supports it).
Also, since you are using linux, I think it would not hard for to read the message from log.

**Comment by VihagChaturvedi** [comment]
> If your current `VO` doesn't support to show this page, then try another one (which supports it). Also, since you are using linux, I think it would not hard for to read the message from log.

Thank you for your response

I am not sure what you mean by trying another `V0`

The logs dont show anything peculiar, it does seem to read the config where the shaders' location is directed, but none of them actually end up loading

I will be attaching the log here if anyone reading this issue can support what I have mentioned

https://pastebin.com/2GaduWs8

**Comment by hooke007** [comment]
Your log shows that you didn't play any file.

**Comment by VihagChaturvedi** [comment]
> Your log shows that you didn't play any file.

cmon mate i am that dumb

**Comment by hooke007** [comment]
At least I cannot found these intial message (like below) about gpu-context....
```
[   0.033][v][vo/gpu/d3d11] Initializing GPU context 'd3d11'
[   0.219][v][vo/gpu/d3d11] Using Direct3D 11 feature level 12_1
[   0.219][v][vo/gpu/d3d11] Device Name: NVIDIA GeForce RTX 2070 Super
[   0.219][v][vo/gpu/d3d11] Device ID: 10de:1e91 (rev a1)
[   0.219][v][vo/gpu/d3d11] Subsystem ID: 1d05:108a
[   0.219][v][vo/gpu/d3d11] LUID: 0000000026bf470f
[   0.219][v][vo/gpu/d3d11] Initializing SPIR-V compiler 'shaderc'
[   0.219][v][vo/gpu/d3d11] Using Direct3D 11.1 runtime
```

**Comment by VihagChaturvedi** [comment]
> At least I cannot found these intial message (like below) about gpu-context....
> 
> ```
> [   0.033][v][vo/gpu/d3d11] Initializing GPU context 'd3d11'
> [   0.219][v][vo/gpu/d3d11] Using Direct3D 11 feature level 12_1
> [   0.219][v][vo/gpu/d3d11] Device Name: NVIDIA GeForce RTX 2070 Super
> [   0.219][v][vo/gpu/d3d11] Device ID: 10de:1e91 (rev a1)
> [   0.219][v][vo/gpu/d3d11] Subsystem ID: 1d05:108a
> [   0.219][v][vo/gpu/d3d11] LUID: 0000000026bf470f
> [   0.219][v][vo/gpu/d3d11] Initializing SPIR-V compiler 'shaderc'
> [   0.219][v][vo/gpu/d3d11] Using Direct3D 11.1 runtime
> ```
> 
> BTW, you were using the deprecated directory "lua-settings", though it does nothing with this issue.


I assume you are using windows, going off of the Direct3D stuff

although, i dont see many things that can vary really

None of the tutorials were linux based , so i am not even sure what is going wrong

I will try and dig into this further, thanks for the help so far, appreciate it :D

**Comment by VihagChaturvedi** [comment]
Update:

uh oh, GPU 0 is not my nvidia gpu apparently...?

```
0.292][v][vo/gpu/x11] X11 opening display: :0
[   0.310][d][vo/gpu/x11] X11 running at 1600x900 (":0" => local display)
[   0.310][d][vo/gpu/x11] Detected wm supports NetWM.
[   0.310][d][vo/gpu/x11] Detected wm supports FULLSCREEN state.
[   0.310][d][vo/gpu/x11] Detected wm supports ABOVE state.
[   0.310][d][vo/gpu/x11] Detected wm supports BELOW state.
[   0.310][v][vo/gpu/x11] Display 0 (HDMI-0): [0, 0, 1600, 900] @ 59.978156 FPS
[   0.310][v][vo/gpu/x11] Current display FPS: 59.978156
[   0.312][v][vo/gpu/vulkan/libplacebo] Probing for vulkan devices:
**[   0.313][v][vo/gpu/vulkan/libplacebo]     GPU 0: llvmpipe (LLVM 13.0.0, 256 bits) (software)**
[   0.314][d][vo/gpu/vulkan/libplacebo]       -> excluding due to params->allow_software
[   0.314][f][vo/gpu/vulkan/libplacebo] Found no suitable device, giving up.
[   0.314][f][vo/gpu/vulkan/libplacebo] Failed initializing vulkan device
```

**Comment by VihagChaturvedi** [comment]
System reboot fixed it :man_facepalming: 

The program now runs properly.

Apparently I had updated my GPU drivers without actually rebooting the system, causing the driver module to be unloaded but not actually being rebuilt. Realised that i havent power cycled my pc in **14 days**
