### ISSUE TITLE
SYNLA_Plus_4096.npy not found

### ISSUE THREAD

**Issue by marcosbitetti** [bloc97/Anime4K#169]
**Describe the bug**
I try to run jupyter code inside nvidia docker, but after all configurations this file not exists anywhere.

**To Reproduce**
- In a jupyter notebook container with tensorflow and nvidia cuda drivers running
- Step 4 of example code raises this error
**Expected behavior**
Running without error

**Screenshots**
This is error on console
![Screenshot_20220403_161956](https://user-images.githubusercontent.com/85936/161444624-e2af7336-3c09-4400-aeff-759b9320da40.png)

This is nvidia information (case it helps)
![Screenshot_20220403_162426](https://user-images.githubusercontent.com/85936/161444630-5663904e-3294-413d-99e7-e0d5073c6a48.png)

**Desktop (please complete the following information):**
 - OS: Docker over Ubuntu Studio 20.10
 - nvidia docker image 22
 - GPU GTX1650

**Comment by bloc97** [comment]
You have to download the small 4096 dataset, extract the tar, then change the path so it is correct: https://github.com/bloc97/SYNLA-Plus/releases

Also please note that the final Anime4K model was not trained using only SYNLA, it is added here for demonstration purposes.

**Comment by marcosbitetti** [comment]
thnks a lot!
