### ISSUE TITLE
Prime Offload & experimental v4.1 SRGAN UUL Shaders doesn't work : [vo/gpu/opengl] after creating texture: OpenGL error INVALID_VALUE

### ISSUE THREAD

**Issue by PowerPixel** [bloc97/Anime4K#175]
**Describe the bug**
While trying to use the command described in [this commit](https://github.com/bloc97/Anime4K/commit/5f9294d847e724b67f941d1742e3565a0a106291), the video playback slowdowns before these error are logged into the console : 
```
 (+) Video --vid=1 (h264 656x480 29.970fps)
 (+) Audio --aid=1 (aac 2ch 44100Hz)
     Subs  --sid=1 --slang=deDE 'ass' (null) (external)
     Subs  --sid=2 --slang=frFR 'ass' (null) (external)
AO: [pulse] 44100Hz stereo 2ch float
VO: [gpu] 656x480 => 661x480 yuv420p
AV: 00:00:02 / 00:24:58 (0%) A-V:  0.016 DS: 4.050/6 Dropped: 18 Cache: 75s/15MB
# Here I use the command in the commit mentionned in the issue
[vo/gpu/opengl] after creating texture: OpenGL error INVALID_VALUE.
[vo/gpu/opengl] after creating texture: OpenGL error INVALID_VALUE.
[vo/gpu/opengl] after creating texture: OpenGL error INVALID_VALUE.
[vo/gpu/opengl] after creating texture: OpenGL error INVALID_VALUE.
[vo/gpu/opengl] after creating texture: OpenGL error INVALID_VALUE.
[vo/gpu/opengl] after creating texture: OpenGL error INVALID_VALUE.
```
No upscaling seems to be applied past this point.

**To Reproduce**
1. Add this line to the `~/.config/mpv/input.conf` file : 
```
CTRL+7 no-osd change-list glsl-shaders set "~~/shaders/Anime4K_Restore_GAN_UUL.glsl:~~/shaders/Anime4K_Upscale_GAN_x4_UUL.glsl:~~/shaders/Anime4K_Restore_CNN_Soft_M.glsl:~~/shaders/Anime4K_Upscale_CNN_x2_M.glsl"; show-text "Anime4K Low Res upscale"
```
2. Launch mpv with the following command : `__NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia mpv https://beta.crunchyroll.com/watch/G6752MM4R/untitled`
3. Press `CTRL + 7` to enable the experimental shaders.

**Expected behavior**
It should apply the shaders without crashing.

**Screenshots**
![image](https://user-images.githubusercontent.com/52136144/170354109-6c741d0e-4d3a-4191-81cf-739be2651f4e.png)

**Desktop (please complete the following information):**
 - OS: Manjaro Linux
 - Version: 5.15.41-1-MANJARO
 - GPU/Version: NVIDIA GeForce RTX 3060 Mobile / Max-Q, proprietary Nvidia Drivers v510.73.05
 - Media Player and Version: mpv v0.34.1-dirty

**Additional context**
I am running mpv on a laptop, using PRIME render offload (which is the official Nvidia OPTIMUS alternative for Linux). Please note that I cannot reproduce the issue without using prime OFFLOAD (with `mpv https://beta.crunchyroll.com/watch/G6752MM4R/untitled`)

**Comment by bloc97** [comment]
Looking at the error logs, it's probably something went wrong with the texture sizes, this error is very common when OpenGL tries to initialize absurd texture sizes unsupported by normal consumer GPUs, like 10000x10000. 

Thanks for reporting this bug, but I don't think I can fix anything in the shaders, as this seems to be a bug either in the drivers or PRIME?

**Comment by PowerPixel** [comment]
> Looking at the error logs, it's probably something went wrong with the texture sizes, this error is very common when OpenGL tries to initialize absurd texture sizes unsupported by normal consumer GPUs, like 10000x10000.
> 
> Thanks for reporting this bug, but I don't think I can fix anything in the shaders, as this seems to be a bug either in the drivers or PRIME?

Hello there !

Thanks for taking the time to answer my bug report. Yeah, I suspect it might be a bug with PRIME Offload or the drivers, although I'm wondering if the problem couldn't come from MPV or GLSL side (sending wrong sizes to the GPU or whatever it does, I'm unfortunately not very knowledgeable when it comes to the graphics side of things :sweat_smile:). Therefore, I'm gonna try to file in a bug for OpenGL before reporting the bug to NVidia.


Thanks again for this wonderful project, and have a nice week !
