### ISSUE TITLE
[Question] A4K performance on Apple silicon?

### ISSUE THREAD

**Issue by QS0x01** [bloc97/Anime4K#185]
Plan to buy a mac mini. Want to know that how a4k perform on mac comparing to Nvidia/AMD platform.

For example. "Anime4K: Mode A (Fast)" 1080p60 -> 2160p60, what about your chip type and gpu usage rate?

Thank you very much for providing information!

**Comment by Jules-A** [comment]
From looking at other issues it doesn't seem to run very well on Apple. There's a guide here and they have to use weak shaders on even the M1 Max...

**Comment by Tama47** [comment]
I'd recommend a Mac mini if you plan to hook it up to your TV as a Home Theater PC. It's definitely the most 'affordable' way to have Anime4K working reliably. If you want to hear my full [experience](https://github.com/bloc97/Anime4K/pull/187#issuecomment-1483638936).
