### ISSUE TITLE
Installation Done. Now... how do i use this thing?

### ISSUE THREAD

**Issue by EndLordMC** [bloc97/Anime4K#188]
Hello everybody

I'm interested in using Anime4K to upscale some short videos. I have followed the Linux installation instructions, and by all means, i should be ready to use it. I understood everything just fine, up until [the usage instructions](https://github.com/bloc97/Anime4K/blob/master/md/GLSL_Instructions_Linux.md#usage-instructions-for-anime4k).

At this point, i have no idea how I'm supposed to utilize Anime4k, I understood basically nothing i read there. My understanding went from **Good** to _Nonexistent_ in just a few seconds.

If anybody would be willing to help me to better understand and utilize Anime4k, I would be most grateful!

OS: Arch Linux

**Comment by EndLordMC** [comment]
Ah, i didn't realize i had to do that through the video player, it thought it was all done through the terminal.
It looks like i got it working now, thank you!

**Comment by Tama47** [comment]
You can also put it in `mpv.conf` to have it automatically select a mode instead of manually turning it on every time.
Something like [**this**](https://github.com/Tama47/Anime4K/blob/master/md/Template/GLSL_Mac_Linux_High-end/mpv.conf).
