### ISSUE TITLE
Reduce soft gradient banding

### ISSUE THREAD

**Issue by DextroseRe** [bloc97/Anime4K#19]
Noticeable color banding in some instances.
![Banding](https://raw.githubusercontent.com/bloc97/Anime4K/master/results/Comparisons/13.png)

**Comment by bloc97** [comment]
Reduced banding in Anime4K v1.0 Release Candidate


![Oversharp](https://raw.githubusercontent.com/bloc97/Anime4K/master/results/Comparisons/0.9-1.0/0_RC.png)
![Oversharp](https://raw.githubusercontent.com/bloc97/Anime4K/master/results/Comparisons/0.9-1.0/1_RC.png)
![Oversharp](https://raw.githubusercontent.com/bloc97/Anime4K/master/results/Comparisons/0.9-1.0/2_RC.png)
![Oversharp](https://raw.githubusercontent.com/bloc97/Anime4K/master/results/Comparisons/0.9-1.0/3_RC.png)
