### ISSUE TITLE
I don't understand how to use it on plex

### ISSUE THREAD

**Issue by Black-Speedy** [bloc97/Anime4K#192]
In the md file for plex it says to input the following code block, but doesn't have any, so I tried the one for both windows and linux and it didn't work. 

ps. running plex on windows

**Comment by bloc97** [comment]
I think the code blocks found in the windows installation guide should work. If you installed plex on a different OS you should use the corresponding code blocks for input.conf.

**Comment by Tama47** [comment]
You can take a look at my step-by-step Windows (GLSL/Plex) guide [**here**](https://github.com/Tama47/Anime4K#installation-instructions).

I think you are confusing `input.conf` and `mpv.conf` with `input.conf.md` and `mpv.conf.md`.
Those are not the same files, you can use my template in the guide and just drag and drop the files in.
<img width="800" alt="config" src="https://user-images.githubusercontent.com/96937943/233772520-918d0dc1-21c9-41c3-a3fb-78ee26d8a3a1.png">
