### ISSUE TITLE
Not so much a feature, but PROPER INSTRUCTIONS. The instuctions are terrible.

### ISSUE THREAD

**Issue by jdc4429** [bloc97/Anime4K#195]
What does this all mean?  It's all gibberish to me.  How do you actually RUN the program? Where is the program?  I installed everything as instructed and see no information on how to run the dam thing.  Can we get a python example on running against an image???

Usage Instructions for Anime4K

    For Anime4K v4.x, instead of activating a single shader, you should use a combination of shaders.
    Add one of the following code blocks to input.conf to allow enabling the shaders:

    Anime4K v4.x has 3 major modes: A, B and C. To enable one of the modes, press CTRL+1 for mode A, CTRL+2 for B and so on. CTRL+0 will clear and disable all the shaders. Each mode is optimized for a different class of anime degradations, explanations are further down (soon in the wiki). For now you can just try each mode (starting from A) and use the one that looks the best.

    To verify the installation was correctly done, enable one of the Anime4K modes and use the MPV profiler to check if there are a few shaders with the name Anime4K running. To access the profiler, press Shift+I and then 2 on the keyboard's top row.
    This is what you should see (this example is from v2.0RC2, but also applies to newer versions):

**Comment by Tama47** [comment]
Please see my [Updated GLSL Instructions](https://github.com/Tama47/Anime4K#installation-instructions) in pull request #190, I've updated it to include templates files. Install is as simple as dragging and dropping files into the right location.

**Comment by Crizomb** [comment]
> Please see my [Updated GLSL Instructions](https://github.com/Tama47/Anime4K#installation-instructions) in pull request #190, I've updated it to include templates files. Install is as simple as dragging and dropping files into the right location.

Still incomprehensible. I'm a little bit stupid (Like a lot of people on Earth. You need to adapte for us) but how do concretely I run the up-scaling ? How do I stop it ? etc...

Instructions still unclear.

**Comment by Tama47** [comment]
> Still incomprehensible. I'm a little bit stupid (Like a lot of people on Earth. You need to adapte for us)

I’m not sure how dragging and dropping files into a location is incomprehensible.

> how do concretely I run the up-scaling ? How do I stop it ? etc...

![image](https://github.com/bloc97/Anime4K/assets/96937943/09cda7d0-c15a-452d-b60f-38b7371d1f94)

You can press CTRL+1 to manually enable it and press CTRL+0 to disable it.

**Comment by ndhanh96** [comment]
maybe try to run the damn thing first. I bet you don't even know what mpv means.
