### ISSUE TITLE
Requesting Deleted Shader (GAN X2 UL)

### ISSUE THREAD

**Issue by AziRizvi** [bloc97/Anime4K#217]
I'd like to request and get the now removed GAN X2 UL shader.
Thank you very much!

**Comment by kato-megumi** [comment]
https://github.com/bloc97/Anime4K/blob/02091fbf0cfeef578e8a25c98601871785e2940b/glsl/Upscale/Anime4K_Upscale_GAN_x2_UL.glsl

**Comment by AziRizvi** [comment]
> https://github.com/bloc97/Anime4K/blob/02091fbf0cfeef578e8a25c98601871785e2940b/glsl/Upscale/Anime4K_Upscale_GAN_x2_UL.glsl

Thank you very much!
Though I wonder why I couldn't see that git branch when I checked it myself.
