### ISSUE TITLE
Anime4k CNN input type

### ISSUE THREAD

**Issue by kristoftunner** [bloc97/Anime4K#226]
I'm curious about why the custom anime4k CNN is not using YUV input images, specifically focusing on the Y component. This approach is quite common in super resolution models due to the reduced sensitivity of our eyes towards chroma components.

The upscaling could be done only on the Y component and for the U/V components a simple bicubic upscale could be used, thus decreasing the computation complexity of the problem.

**Comment by hooke007** [comment]
> I'm curious about why the custom anime4k CNN is not using YUV input images

Anime4k v3.0
