### ISSUE TITLE
Upscale filter no longer working - unsure why

### ISSUE THREAD

**Issue by roseyhead** [bloc97/Anime4K#232]
**Describe the bug**
A few weeks back I set up Anime4K HQ on an existing Plex HTPC install. Worked great at the time but at some point I noticed the upscale filter had stopped working, as in no visual difference in sharpness between A/B/C/Off. There were some changes in contrast with the filters on and off due to Anime4K_Clamp_Highlights.glsl so I can verify that Anime4K in general works. 
For example I played around with input.conf and created a couple of custom profiles with a mix of filters - if I create a new profile the same as A but without Anime4K_Clamp_Highlights.glsl there is zero visual difference with that turned on or off.
Also tried completely reinstalling Plex HTPC and removing the localappdata folder but made no difference.

**To Reproduce**
1. Download GLSL_Windows_High-end.zip and extract to %localappdata%/Plex HTPC
2. Open Plex, open a video
3. Toggle between A/B/C/off
4. Anime4K_Clamp_Highlights.glsl works but Anime4K_Upscale_CNN_x2_VL.glsl makes no visible difference

**Expected behavior**
Fileter combination should sharpen lines

**Screenshots**
I'm logging this while at work so I don't have any screenshots (not sure they should be necessary) but can provide if required

**Desktop (please complete the following information):**
 - OS: Windws 11
 - Version: 22H2
 - GPU/Version: RTX4080 on 551.23
 - Media Player and Version: Plex HTPC 1.54.0
 - Browser: n/a

**Additional context**
I'm not sure what might have changed, except for migrating my Plex server install from an Ubuntu PC to Docker on a Debian PC but that shouldn't make a difference, right?

**Comment by Tama47** [comment]
Can you verify by checking the profiler if Anime4K is running?
<img width="1470" src="https://github.com/bloc97/Anime4K/assets/96937943/250ff167-3384-421a-9bad-38edb6093fb8">

Add this line to your ```input.conf``` inside ```%LOCALAPPDATA%\Plex HTPC```. Then quit and reopen Plex HTPC.
```
i script-binding stats/display-stats-toggle
```
Press ```i```, and then press ```3```. It should show all the shaders being rendered.

Also, keep in mind that ```Anime4K_Upscale_CNN``` shaders only upscale the resolution ```1080p > 2160p```. The shaders that are responsible for sharpening lines are the ```Anime4K_Restore_CNN``` shaders.

**Comment by roseyhead** [comment]
Hey! Thanks for the response. I've turned that on and grabbed a couple of screenshots. Here's a screenshot with the default A filters enabled:
![a default filter](https://github.com/bloc97/Anime4K/assets/10427811/e6b25bfc-bb9f-4a0c-b176-6310263f706c)

And one with them disabled:
![filters off](https://github.com/bloc97/Anime4K/assets/10427811/fe416fdf-3148-4cff-821f-f58b05c4c2d9)
Magenta's a very slightly different shade of magenta in each

For comparison's sake, here's a shot with only Anime4K_Clamp_Highlights.glsl enabled:
![just clamp highlights](https://github.com/bloc97/Anime4K/assets/10427811/85781bb8-6f92-4914-8a8d-3bb99c55c906)

And a shot with only Anime4K_Restore_CNN_VL.glsl x3 (i'd expect this to oversharpen massively? or at least have some effect)
![just restore 3x](https://github.com/bloc97/Anime4K/assets/10427811/93133b87-7d90-4fa2-a7df-af59ce01d3a9)

The only difference I can see is a slight change in contrast in parts of the image when the clamp filter is on. Also, just to clarify, this is all 1080p video played on a 2160p screen. Like I said it definitely worked the first time I set it up, so I know how it's meant to look!

**Comment by Tama47** [comment]
Lovely screenshots of Magenta!

Anyway, it seems like the shaders are active and running normally. I do see that there's not much difference between having the shaders on or off, aside from the slight contrast. I'm running the latest version of Plex and Plex HTPC on both Mac and Windows systems, and Anime4K still works fine. So, I highly doubt this is an issue with the Plex app itself.

Just to isolate the issue, could you try running the shaders in mpv or the normal Plex app and see if Anime4K is working correctly there? Also, try downloading the shaders again directly from [Releases](https://github.com/bloc97/Anime4K/releases/tag/v4.0.1), as there could be something wrong with the files. You could also try using these combined preset [shaders](https://github.com/mikigal/Anime4K-GUI/tree/master/resources/shaders) and see if they work.

**Comment by roseyhead** [comment]
Thanks, in hindsight it was kinda dumb of me not to try Plex Desktop and MPV before creating an issue. The shaders did the same thing on Plex but MPV worked as expected, which caused me to remember that at some point I'd replaced the Plex mpv library via this guide:
https://forums.plex.tv/t/htpc-tips-and-tricks/794228/3
Dropped in the latest mpv-2.dll and it's all working great. Looking at my browser history I did this AFTER originally installing Anime4k though, so could be that's what broke it in the first place? At any rate that's fixed it this time so I'm happy. Thanks for your help :)

**Comment by Tama47** [comment]
That’s interesting! I didn’t even realize you could replace the mpv library in Plex. Maybe I’ll give it a try, since I do want to use their new library and I’ll see if it breaks Anime4K too. Anyway, glad it worked out for you!

**Comment by Tama47** [comment]
So I just replaced the old libmpv in Plex HTPC with the new one, and Anime4K seems to be working for me.

Old libmpv on Mac:
<img width="1920" alt="Screenshot 2024-02-11 at 04 30 38" src="https://github.com/bloc97/Anime4K/assets/96937943/0eb9e78f-7872-4026-b7f6-30e374bc7172">

New libmpv on Windows:
Anime4k Off
<img width="1920" alt="Screenshot 2024-02-11 at 04 33 49" src="https://github.com/bloc97/Anime4K/assets/96937943/1b3e8bf1-8310-4402-87d0-6177837e57dc">
Anime4K On
<img width="1920" alt="Screenshot 2024-02-11 at 04 32 43" src="https://github.com/bloc97/Anime4K/assets/96937943/b9dd7c63-a037-4278-9f73-b1ea23b0b30a">
<img width="1920" alt="Screenshot 2024-02-11 at 04 32 54" src="https://github.com/bloc97/Anime4K/assets/96937943/a2b6dffa-0c0c-4eea-beeb-cf22c1590974">

**Comment by roseyhead** [comment]
Little FYI - Plex HTPC updated today and I noticed Anime4K broken the same way as it was when I opened this issue - replaced mpv-2.dll the same way which immediately fixed it.

**Comment by Tama47** [comment]
Yep, the same thing happened to me. Although, I replaced it with the new libmpv and it works just fine. What concerns me, though, is that I will need to keep replacing the mpv-2.dll file every time there is an update. Which would be pretty annoying as Plex updates pretty often, and I didn't have this issue prior to changing the mpv-2.dll file. But the trade-off might be worth it for the new libmpv alone, considering that Plex still uses the old mpv library.
