### ISSUE TITLE
My movies aren't being improved properly

### ISSUE THREAD

**Issue by 0xdeada55** [bloc97/Anime4K#25]
**Describe the bug**
I passed this over my hentai and it didn't made me nut faster, what the fuck!

**To Reproduce**
1. Get your hentai
2. Pass this boi over it
3. Watch it and see what you last
4. No nut in wanted time range, expected: < 20s got: > 20s

**Expected behavior**
A big nut in less than the previous best time

**Screenshots**
![activated+nut](https://user-images.githubusercontent.com/53819159/63453594-51783580-c449-11e9-8854-422f4c78f8aa.PNG)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Arch Linux with some fancy tiling WM
 - Browser [e.g. chrome, safari] chrome
 - Version [e.g. 22] the one and only latest

**Additional context**
inconceivable!

**Comment by bloc97** [comment]
Troll issue.

**Comment by 0xdeada55** [comment]
how you dare classify the existance of this issue as "troll" :3 uwu
