### ISSUE TITLE
Shaders make no difference on or off?

### ISSUE THREAD

**Issue by evergoof** [bloc97/Anime4K#252]
When turning on or switching between anime4K modes on mpv there is no visible difference.

Steps to reproduce:
Open mpv
Press your Anime4K shader keys

No Shaders:
![AnimeRG  Berserk - 02  Dual Audio   1080p   x265   pseudo mkv-00 09 35 366-#1](https://github.com/user-attachments/assets/f9450d49-6863-4dc2-a535-5524dbe84900)
Anime4K Mode B:
![AnimeRG  Berserk - 02  Dual Audio   1080p   x265   pseudo mkv-00 09 35 366-#2](https://github.com/user-attachments/assets/f2e2a055-1283-4ac6-b13a-a2a344de9365)
No Shaders:
![Judas  Zankyou no Terror - 04 mkv-00 09 58 688-#1](https://github.com/user-attachments/assets/f581c477-38dc-4f96-b7e8-6839fe9e8d91)
Anime4K Mode A:
![Judas  Zankyou no Terror - 04 mkv-00 09 58 688-#2](https://github.com/user-attachments/assets/d9689515-0093-4702-920c-eff0d7e9450a)

OS: Nobara Linux
RTX 3060 560.53.03

**Comment by Jules-A** [comment]
Those images are tiny, you are probably trying to use a resolution less than 1.2x the video's resolution. (it won't activate because of this check in the shaders `//!WHEN OUTPUT.w MAIN.w / 1.200 > OUTPUT.h MAIN.h / 1.200 > *` ).
