### ISSUE TITLE
1080p->1440p ,it is possible?

### ISSUE THREAD

**Issue by JosephNew** [bloc97/Anime4K#43]
4K display is too big,not suitable for PC
2K is a more good and useful.
Does anime4K can change 1080P to 1440P?

**Comment by Calinou** [comment]
It seems to work well in the GLSL variant which I'm using in mpv. It doesn't look as good as going from 1080p to 4K, but it's still an improvement. I also made mpv use Lanczos filtering (instead of the default Spline) to further smooth out upscaling:

```text
scale=ewa_lanczossharp
cscale=ewa_lanczossharp
glsl-shaders="~~/shaders/Anime4K_Adaptive.glsl"
```

**Comment by bloc97** [comment]
1080p to 1440p now looks much better using the latest version, v2.0 RC (Experimental), due to reduced aliasing. 720p->1080p and 1080->1440p upscaling is now officially supported.
