### ISSUE TITLE
Will there be an update for the hlsl version?

### ISSUE THREAD

**Issue by Artins90** [bloc97/Anime4K#47]
Hi, I have been using your algorithm on top of NGU for the past 3 months or so.
I have noticed that the hlsl version has not been updated in quite a while.
I tried to convert the glsl shader to hlsl using glslang and SPIRV-Cross but I failed.
I would like to know if you are going to update the hlsl version in the future or if there is an easier way to convert the glsl shader.

**Comment by amayra** [comment]
i went to know i prefer to use madvr+player than MPV

**Comment by bloc97** [comment]
I cannot find MPC documentation about HLSL. Currently the GLSL code uses 3-4 extra textures to store intermediate values, but HLSL only provides one extra memory variable (the alpha channel).

However I think it would be possible to store multiple values in that single alpha channel by compressing the variables, but the quality won't be equal to the GLSL version.

**Comment by rxvincent** [comment]
So the GLSL version has better effect at this time?

**Comment by bloc97** [comment]
Version 0.9 for GLSL and HLSL have the same quality, but v1.0RC for GLSL has better quality.

**Comment by petronny** [comment]
I find a project called [glslcc](https://github.com/septag/glslcc) which may do the glsl -> hlsl convertion.
But I'm not familiar with neither glsl or hlsl.

Currently I'm facing the following issues when doing the glsl -> hlsl convertion with glslcc:
1. I have to specific the shader type (eg. vertex, fragment and compute shaders) and I don't know which types the Anime4K shaders are.
1. I tried each shader type for `Anime4K_Auto_Downscale_Pre_x4.glsl`:
```
$ glslcc -v Anime4K_Auto_Downscale_Pre_x4.glsl --lang=hlsl -o Anime4K_Auto_Downscale_Pre_x4.hlsl
:0:0: error: Anime4K_Auto_Downscale_Pre_x4.glsl:36: 'HOOKED_pos' : undeclared identifier
Anime4K_v3.1/Anime4K_Auto_Downscale_Pre_x4.glsl:36:0: error: 'HOOKED_tex' : no matching overloaded function found
Anime4K_v3.1/Anime4K_Auto_Downscale_Pre_x4.glsl:36:0: error: '' : compilation terminated

$ glslcc -f Anime4K_Auto_Downscale_Pre_x4.glsl --lang=hlsl -o Anime4K_Auto_Downscale_Pre_x4.hlsl
:0:0: error: Anime4K_Auto_Downscale_Pre_x4.glsl:35: 'float' : type requires declaration of default precision qualifier
Anime4K_v3.1/Anime4K_Auto_Downscale_Pre_x4.glsl:35:0: error: '' : compilation terminated

$ glslcc -c Anime4K_Auto_Downscale_Pre_x4.glsl --lang=hlsl -o Anime4K_Auto_Downscale_Pre_x4.hlsl
:0:0: error: #version: statement must appear first in es-profile shader; before comments or newlines
Anime4K_v3.1/Anime4K_Auto_Downscale_Pre_x4.glsl:36:0: error: 'HOOKED_pos' : undeclared identifier
Anime4K_v3.1/Anime4K_Auto_Downscale_Pre_x4.glsl:36:0: error: 'HOOKED_tex' : no matching overloaded function found
Anime4K_v3.1/Anime4K_Auto_Downscale_Pre_x4.glsl:36:0: error: '' : compilation terminated
```
And all of them failed. Is there any suggestion to solve these errors?

**Comment by TianZerL** [comment]
@petronny
The problems is not the convertion from glsl to hlsl. DirectShow based players like MPC-HC, BE and potplayer do not support to save data to a temporary texture, this is the crux of the matter, it is impossible to implement the Anime4K CNN algorithm in hlsl for DirectShow based players now.

**Comment by bloc97** [comment]
It would technically be possible to implement the entire shader stage in a single pass without the use of temporary textures, but that would increase the computational complexity from O(n) to O(n^s) for s spatially separated stages. A O(n^8) complexity is impossible to work with for anything larger than 480p...

**Comment by Jules-A** [comment]
> The problems is not the convertion from glsl to hlsl. DirectShow based players like MPC-HC, BE and potplayer do not support to save data to a temporary texture, this is the crux of the matter, it is impossible to implement the Anime4K CNN algorithm in hlsl for DirectShow based players now.

Is it just for the shaders using CNN? If so could the ones that don't use it be converted without the complexity increase bloc97 mentioned?

**Comment by JackBool** [comment]
> @petronny
> The problems is not the convertion from glsl to hlsl. DirectShow based players like MPC-HC, BE and potplayer do not support to save data to a temporary texture, this is the crux of the matter, it is impossible to implement the Anime4K CNN algorithm in hlsl for DirectShow based players now.

请问Anime4K 3.1版本可以从GLSL转换为HLSL吗？
Can Anime4K version 3.1 be converted from GLSL to HLSL? I have the same problem as @petronny when using the glslang.  
The 0.9 hlsl version doesn't work well with mpc-be & potplayer on my device.(ps: it doesn't show any difference after using the v0.9 hlsl shaders when playing video, but v3.0 glsl shaders works well with mpv) 
Is v0.9 just not very efficient or some else reason？

**Comment by TianZerL** [comment]
@JackBool
不可以，两个播放器并不是只是着色器语言不一样，提供的API也不一样，并且正如我说过的基于DirectShow的播放器并不支持着色器保存临时纹理，所以除非人工重写并且解决临时纹理的问题，否则不可能直接转换。  
No, direct conversion is not possible, the difference between the two players is not just in the different shader language.
