### ISSUE TITLE
Burned-In Subtitles on Videos looks weird when compared with other upscaler

### ISSUE THREAD

**Issue by Tsubajashi** [bloc97/Anime4K#49]
**Describe the bug**
Burned-In Text on Video looks weird when compared with other upscaler.

**To Reproduce**
1. Open Any Video with burned-in Subs with mpv
2. See error

**Expected behavior**
Good Readable Text.

**Screenshots**
https://imgur.com/a/XrHuHKV

 - OS: Windows 10
 - Version 1.0rc2
 - Media Player: MPV (latest shinchiro build mpv-x86_64-20191013-git-a85fa2d)

**Comment by bloc97** [comment]
This will be fixed in the experimental AnimeSR variant of Anime4K using machine learning. It is currently very difficult to fix this in the vanilla algorithm due to its simplicity.

**Comment by Tsubajashi** [comment]
@bloc97 Sounds alright, thanks!

**Comment by bloc97** [comment]
Fixed in latest version, v2.0 RC (Experimental).
![image](https://user-images.githubusercontent.com/567732/75649376-e93cb480-5c20-11ea-9236-0899cc657f5e.png)
