### ISSUE TITLE
Please support android 

### ISSUE THREAD

**Issue by onexuan** [bloc97/Anime4K#54]
Please support android

**Comment by stefnotch** [comment]
The web demo should work on Android. 
Also, the GLSL shader is platform independent and as such, Android is already a supported platform.

**Comment by tjgordon** [comment]
Do you know how to use the shader on android-mpv? The mpv config file is editable in settings, but where should the shader file be placed?

**Comment by Calinou** [comment]
> Also, the GLSL shader is platform independent and as such

Does it work on OpenGL ES though? GLSL ES has much less features compared to full GLSL.
