### ISSUE TITLE
How to use it on a single image upscaling?

### ISSUE THREAD

**Issue by ashoka89** [bloc97/Anime4K#56]
and can this algorithm remove noise from image??
thank you

**Comment by bloc97** [comment]
You can try the Java version for single image upscaling, but keep in mind that the Java version is currently outdated. The main goal of this project is to upscale video in real time. Single image upscaling is best done with other algorithms that focus on quality (such as EDSR, VDSR, waifu2x, etc.).

This algorithm does not remove noise, but doesn't amplify it either.

**Comment by ashoka89** [comment]
thank you
