### ISSUE TITLE
Add //!DESC Anime4K

### ISSUE THREAD

**Issue by GreyWing3** [bloc97/Anime4K#6]
Currently when looking at stats in mpv this shader has no proper name
shows:
`user shader:(unknown)`

By adding //!DESC Anime4K
shows:
`user shader:Anime4k`

Needs to be added to each set
```
//!HOOK SCALED
//!BIND HOOKED
//!BIND POSTKERNEL
//!SAVE POSTKERNEL
```

**Comment by bloc97** [comment]
Accepted merge request, closing issue.
