### ISSUE TITLE
Update for GLSL (v2.0 Release Candidate) Experimental

### ISSUE THREAD

**Issue by Tall-Lobster** [bloc97/Anime4K#63]
I tested it out and it seems to be using the gpu as intended.

However, I am not sure if it occurs that in times the entire frame looks like it was upscaled bilinearly, while at other times it feels like the image is significantly improved. I have tested it by moving back and forth between the video and on video formats smaller than 480p and it seems to be working, but not much effect had applied to those videos since they have a small resolution

**Comment by bloc97** [comment]
If you post a few screenshots we could look into it. (Provide the original + your results) But please be aware that old 480p anime are notoriously hard to upscale. They are often very blurry due to the quick production process.

**Comment by Tall-Lobster** [comment]
Dear @bloc97 
please help me set up anime4k with mpv because it turns out anime4k was not set up correctly

#62

**Comment by Tall-Lobster** [comment]
i figured out the issue but now I know what I have to do. I just realized I should run my videos through a denoiser or a filter that clears out errors. I was wondering if you are aware of any tools that can do that?

**Comment by bloc97** [comment]
Anime4K v2.0 RC4 and RC5 has a built-in a denoiser. RC5 is sharper than RC4 but might introduce aliasing. Try out both and pick the one that you think looks better.

**Comment by Tall-Lobster** [comment]
> 
> 
> Anime4K v2.0 RC4 and RC5 has a built-in a denoiser. RC5 is sharper than RC4 but might introduce aliasing. Try out both and pick the one that you think looks better.

thanks for the info, I will try the new releases out and see what I like
