### ISSUE TITLE
How to use it in SMPlayer?

### ISSUE THREAD

**Issue by wdw89** [bloc97/Anime4K#64]
SMPlayer is a GUI of Mplayer and mpv, I can add option of mpv in advanced preference, but has no effect with Anime4K. Is there any one know how to use?

**Comment by Jasperabez** [comment]
Edit the mpv.conf file to include the line to enable the shaders, then in SMPlayer Options>Preferences>MPlayer/mpv there's a blank fill for "Options:" 

In the field enter 
```
--config=yes
```

this should allow the shader to work there, as the config file is disable by default in SMPlayer

**Comment by orehkt** [comment]
For the current version of Anime4K shaders and SMP 20.6

I put shaders here on windows 
<details>
  <summary>Expand to see the image</summary>

![image](https://user-images.githubusercontent.com/67135495/85095441-66d00480-b1bf-11ea-95c6-079d9afedc85.png)
</details>

And pass one of the 6 readme configs in the` Options: ` field (with the -- and the correct route), for example the last setting for 1080p on the readme
- Improve perceptual quality + deblur:  
 `--glsl-shaders="~~/mpv/shaders/Anime4K_Denoise_Bilateral_Mode.glsl;~~/mpv/shaders/Anime4K_Deblur_DoG.glsl;~~/mpv/shaders/Anime4K_DarkLines_HQ.glsl;~~/mpv/shaders/Anime4K_ThinLines_HQ.glsl;~~/mpv/shaders/Anime4K_Upscale_CNN_M_x2_Deblur.glsl"`

<details>
  <summary>See the other configs</summary>

For 480/720p videos:
 - Remain as faithful to the original while enhancing details:  
 `--glsl-shaders="~~/mpv/shaders/Anime4K_Upscale_CNN_L_x2_Denoise.glsl;~~/mpv/shaders/Anime4K_Auto_Downscale_Pre_x4.glsl;~~/mpv/shaders/Anime4K_Upscale_CNN_M_x2_Deblur.glsl"`
 - Improve perceptual quality:  
 `--glsl-shaders="~~/mpv/shaders/Anime4K_Upscale_CNN_L_x2_Denoise.glsl;~~/mpv/shaders/Anime4K_Auto_Downscale_Pre_x4.glsl;~~/mpv/shaders/Anime4K_DarkLines_HQ.glsl;~~/mpv/shaders/Anime4K_ThinLines_HQ.glsl;~~/mpv/shaders/Anime4K_Upscale_CNN_M_x2_Deblur.glsl"`
 - Improve perceptual quality + deblur:  
 `--glsl-shaders="~~/mpv/shaders/Anime4K_Upscale_CNN_L_x2_Denoise.glsl;~~/mpv/shaders/Anime4K_Auto_Downscale_Pre_x4.glsl;~~/mpv/shaders/Anime4K_Deblur_DoG.glsl;~~/mpv/shaders/Anime4K_DarkLines_HQ.glsl;~~/mpv/shaders/Anime4K_ThinLines_HQ.glsl;~~/mpv/shaders/Anime4K_Upscale_CNN_M_x2_Deblur.glsl"`

For 1080p videos:
 - Remain as faithful to the original while enhancing details:  
 `--glsl-shaders="~~/mpv/shaders/Anime4K_Denoise_Bilateral_Mode.glsl;~~/mpv/shaders/Anime4K_Upscale_CNN_M_x2_Deblur.glsl"`
 - Improve perceptual quality:  
 `--glsl-shaders="~~/mpv/shaders/Anime4K_Denoise_Bilateral_Mode.glsl;~~/mpv/shaders/Anime4K_DarkLines_HQ.glsl;~~/mpv/shaders/Anime4K_ThinLines_HQ.glsl;~~/mpv/shaders/Anime4K_Upscale_CNN_M_x2_Deblur.glsl"`
</details>

<details>
  <summary>Expand to see the image</summary>

![image](https://user-images.githubusercontent.com/67135495/85095663-13aa8180-b1c0-11ea-9fc4-1d53ff492ed8.png)
</details>

If you want to use the keyboard shortcuts of the readme, the only option is check the `Run MPlayer/mpv on its own windows, ` and edit the config files in mpv folder.

**Comment by wdw89** [comment]
Thank you, after some test, I need to add --vo=gpu first
