### ISSUE TITLE
V2 produces significantly worse image quality than V1

### ISSUE THREAD

**Issue by cladoxylopsidus** [bloc97/Anime4K#65]
![2020-03-01-071657_3840x2160_scrot](https://user-images.githubusercontent.com/61645384/75621107-c19e0b80-5b90-11ea-88a0-a32b2ff8ebe1.png)
V1

![2020-03-01-073022_3840x2160_scrot](https://user-images.githubusercontent.com/61645384/75621123-0cb81e80-5b91-11ea-833e-bc8305c92c95.png)
V2

In V2 the lines are as blurry as can get. The new algorithm is a mistake.

**Comment by bloc97** [comment]
For some reason the algorithm is not running in your setup. I suggest checking the profiler in MPV with Shift-I then press 2. If you don't see a few Anime4K shaders in there it is not running correctly. Here's what I get on my end.

![75621123-0cb81e80-5b91-11ea-833e-bc8305c92c95_a4kv2](https://user-images.githubusercontent.com/567732/75621218-a8c93200-5b5f-11ea-8759-a97062652ddd.jpg)

**Comment by bloc97** [comment]
I will close this. If you still have problems, feel free to re-open this issue.
