### ISSUE TITLE
Wonder if the glsl is properly setup

### ISSUE THREAD

**Issue by zluo01** [bloc97/Anime4K#67]
I follow the instruction and check the profile.
![Screenshot from 2020-03-01 20-17-37](https://user-images.githubusercontent.com/12102011/75640225-e24e7b80-5bf9-11ea-9638-f712b1a1c226.png)
As the image shows, it shows different shaders, but no usage ?
Thus, I wonder if the shaders are actually working.

Thank you

**Comment by bloc97** [comment]
Which version of MPV are you using and what GPU do you have?
Also you could simply take a screenshot of the original video (windowed mode), and then compare it to the upscaled version (full screen). If there's significant improvement, the algorithm is running.

**Comment by zluo01** [comment]
0.31 and a 2080ti. it seems a little bit sharper, but I am not sure.
With shaders,
![Screenshot from 2020-03-02 13-36-32](https://user-images.githubusercontent.com/12102011/75710917-1160fd80-5c8b-11ea-993e-f07955b677cf.png)
Without shaders
![Screenshot from 2020-03-02 13-37-00](https://user-images.githubusercontent.com/12102011/75710939-1de55600-5c8b-11ea-9e7e-6bbb4a6f3470.png)

Thank you

**Comment by bloc97** [comment]
It looks like it is working in your screenshot.
If for some reason you find it not sharp enough (some anime are just softer), you can decrease the `ANTIALIAS_STRENGTH` parameter in the shader.
You can find it at line 381:
`#define ANTIALIAS_STRENGTH 0.34`
Decrease it to 0.3 (very sharp) or even 0.2 (extremely sharp).

**Comment by zluo01** [comment]
Ok, thank you very much.
