### ISSUE TITLE
Refinement pass is run on unscaled video

### ISSUE THREAD

**Issue by dixie-flatliner** [bloc97/Anime4K#68]
When using the version 2.0RC2 version of the shader, the final pass (Anime4K-Hybrid-Refine-v2.0RC2) is run on unscaled or downscaled video.

I would expect nothing at all to be run in these situations.

Tested on Windows 10 20H1 with v.2.0RC2 and mpv version 0.31 and 0.32. 

(On a side note, the shader seems to work perfectly well with mpv 0.32 using the Vulkan and OpenGL backends-- it seems only the D3D11 backend is affected.)

**Comment by bloc97** [comment]
I'm unsure how this is occurring. There's a line in the shader that skips the shader if the Luma channel is no less than 1.2x the size of the viewing resolution.

**Comment by dixie-flatliner** [comment]
Downloaded the shader again, and lo and behold nothing's run, just as expected.

Was _absolutely_ sure I hadn't messed with the file, but apparently I just managed to forget about it. My bad.
