### ISSUE TITLE
How to process it with ffmpeg?

### ISSUE THREAD

**Issue by xpirad** [bloc97/Anime4K#72]
I want to pre-process the video using ffmpeg with anime4k glsl so that i can watch it on potplayer( which doesn't seem to support glsl, sadly) .

Can you give some instruction on how to achieve that (preferably with gpu support)?

Thanks!!

**Comment by xpirad** [comment]
I found a thread on this, but there doesn't seem to be any detailed instruction there

https://forum.processing.org/two/discussion/20227/processing-video-with-a-glsl-shader-and-saving-the-video

**Comment by bloc97** [comment]
I will release the python/tensorflow version soon. It will be then possible to use with ffmpeg-python. However I do not think it will work with potplayer.

**Comment by xpirad** [comment]
OK, thanks!
