### ISSUE TITLE
It doesn't work normally on MPV

### ISSUE THREAD

**Issue by NoneMore** [bloc97/Anime4K#73]
It seems that mpv has loaded the shader but it didn't work well
![QQ截图20200324155013](https://user-images.githubusercontent.com/31123633/77401031-2a228600-6de7-11ea-9df2-becb9da49805.png)

**Comment by Tsubajashi** [comment]
What’s the resolution of your video file compared to your display resolution?

**Comment by NoneMore** [comment]
> 
> 
> What’s the resolution of your video file compared to your display resolution?

720p to 1080p

**Comment by Tsubajashi** [comment]
Your Screenshot isnt fully 1080p.
Is it windowed and not fullscreen? i think it only reacts if you really fullscreen on 1080p if you watch 720p stuff.

**Comment by NoneMore** [comment]
> 
> 
> Your Screenshot isnt fully 1080p.
> Is it windowed and not fullscreen? i think it only reacts if you really fullscreen on 1080p if you watch 720p stuff.

Well,you're right.It works.
