### ISSUE TITLE
MPV pink everytime

### ISSUE THREAD

**Issue by whwfxd** [bloc97/Anime4K#75]
**Describe the bug**
When playing video with GLSL (v2.1 Stable), it only displays pink, and neither the full screen nor the window can not work.The player screenshot is below.
The previous version workes fine.
Thanks for attention.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Version [GLSL (v2.1 Stable)]
 - Media Player (If applicable) [ MPV v0.31]
![mpv-screenshot-NEKOPARA 09 mp4-00_00_03](https://user-images.githubusercontent.com/44220906/77518932-91106f80-6eb9-11ea-9b0a-c2ab712801d3.jpg)

**Additional context**

**Comment by bloc97** [comment]
What GPU do you have? It might be out of memory, or something else causes textures to be invalid.

**Comment by whwfxd** [comment]
> 
> 
> What GPU do you have? It might be out of memory, or something else is causing textures to be invalid.

At the beginning I used the integrated graphics of the laptop, which can work normally when using the opengl api. After switching to NVIDIA 1650, opengl and d3d11 api can work well. But the vulkan api always does not work

**Comment by bloc97** [comment]
Integrated graphics are too weak to run these shaders, and there are inconsistencies when using different APIs such as Vulkan or DirectX, but that's a issue for mpv to solve.

So, I assume it is working now, right? I will close this. Feel free to re-open it if there are any further issues.
