### ISSUE TITLE
No visual improvement

### ISSUE THREAD

**Issue by kylesgl** [bloc97/Anime4K#76]
**Describe the bug**
Using 1080p video source with GLSL v2.1 & v2.1a doesn't seem to "work" compared to v2.0RC5. Output looks the same with or without the v2.1 shader. 

**Screenshots**
![Untitled](https://user-images.githubusercontent.com/60184667/77838593-e91ece80-7164-11ea-82ac-65f9149d5e4a.png)
![Untitled2](https://user-images.githubusercontent.com/60184667/77840699-d5319780-7179-11ea-9421-725f8d315903.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: v2.1/v2.1a
 - GPU: GTX 1060
 - Media Player and Version: MPV v0.31 (20191229)

**Comment by Tsubajashi** [comment]
So what’s your screen resolution?
Anime4k starts up. But it seems like you use a 1080p Monitor, right?

**Comment by kylesgl** [comment]
@Tsubajashi Yep 1080p screen.

**Comment by Tsubajashi** [comment]
Then the Upscaling does not take place as it doesnt make sense to update 1080p anime source to a 1080p screen, even if you downscale. its intended behaviour.

**Comment by bloc97** [comment]
It looks like that CAS was applied even when not upscaling in the older 2.0 versions. That was not intended, even if the image can "look" better in some cases, it will oversharpen scenes or anime that are already very sharp.

**Comment by Jules-A** [comment]
Is it possible to have an easily configurable toggle to enable it even when not up-scaling but with a lower sharpness value?
