### ISSUE TITLE
Consulting cooperation

### ISSUE THREAD

**Issue by linziyang1106** [bloc97/Anime4K#79]
We are eager to introduce this animation video enhancement technology product to the Chinese mainland for market operation. My email address is linzy1113@gmail.com. I am looking forward to your reply.

**Comment by bloc97** [comment]
What's this about? Anime4K code is licensed by default under the MIT license, which allows commercial use, as long as the code stays open and the license does not change.
I currently have no intention of making or allowing any proprietary versions of Anime4K.

**Comment by Calinou** [comment]
> Anime4K code is licensed by default under the MIT license, which allows commercial use, as long as the code stays open and the license does not change.

The MIT license does allow sublicensing, which means proprietary software can incorporate it. Someone could even make a proprietary Anime4K fork (even if that's unlikely and ill-advised).

**Comment by bloc97** [comment]
> The MIT license does allow sublicensing, which means proprietary software can incorporate it. Someone could even make a proprietary Anime4K fork (even if that's unlikely and ill-advised).

Of course anyone is welcome to fork and incorporate into proprietary software, but the license has to be included. If someone does significant research and modifications to the algorithm, they should have the right to publish his improved algorithm in a proprietary license. (But the original MIT license still has to be included as it is a derivative of the original Anime4K.)

What I was referring to when mentioning "no intention of making or allowing any proprietary versions" was that I am not looking forward to make a new version of Anime4K and then licensing it to a company/entity under a proprietary license.
As of right now all my intentions are to improve Anime4K while keeping it under an open license.
