### ISSUE TITLE
Strange performance hit with 480p videos

### ISSUE THREAD

**Issue by mhtvsSFrpHdE** [bloc97/Anime4K#80]
The Nvidia 1050 Ti video card

I got 60 fps while playing 720 and 1080 videos, only with 480 videos  
the fps drop to around 42 at all time

Change MPV player scale algorithm to nearest to see if this is the MPV issue but not helped.

**Comment by bloc97** [comment]
Which version of the shader are you using? If it is the v2.1aL version, it is normal. 1050Ti might not be strong enough to run the x4 upscaler.
But anime are usually 30 or 24fps, it shouldn't be a problem?

**Comment by mhtvsSFrpHdE** [comment]
@bloc97 The fact is 24fps converted to 60fps(60 Hz monitor) and then result in 42/60fps,  
this cause some frames are dropped  
```
24/60=0.4
42*0.4=16.8
24-16.8=7.2
```
I'm use the v2.1aL, what do I supposed to do?  
Grab a h.264 tool to convert 480p videos to 720?  
If apply 720p algorithm to 480p information videos, is this bad?  
Or just use v2.1a but not L?

**Comment by chrnodroid** [comment]
I have a GTX 1060, so is not so many stronger than a 1050Ti,  and I also use the v2.1aL. 
480p anime works like a charm, gpu usage is only 1.2%. 
But are you talking about 60 fps anime with motion interpolation like SVP ? That is an overkill for the gpu.

**Comment by lux-perpetua** [comment]
I've tested 420p video with two passes of v2.1aL with temporal interpolation, debanding and anti-ringing on 1050 (mobile) and it works just fine on 1080p@60Hz OpenGL output. The reported utilization was less than 40% even with lower clocks("optimal power" in Nvidia control panel). The video output looked really ugly, but I haven't noticed any performance hit (except when I was plugged out from power and I believe that GPU was memory bandwidth constrained due to even lower clocks).

**Comment by mhtvsSFrpHdE** [comment]
@chrnodroid @lux-perpetua  @bloc97  
I'm not using any kind of SVP-like smooth plugin, but that reminds me!  
I then just checked my `mpv.conf`, and noticed something like:
```
# Interpolation
video-sync=display-resample
tscale=oversample
```
Well I didn't realize that would be a heavy performance option...  
I was thought it is "non-integer frame interval conversion",  
when I use other media player this feature is almost zero-performance hit.

After comment the two lines out, everything is fine and I got 0 frames drop!  
Thank you!

**Comment by chrnodroid** [comment]
@mhtvsSFrpHdE 
Ah, the interpolation option! It's very heavy yes, maybe 
`tscale=mitchell`
is less heavy than oversample.
I always prefer to not using the interpolation because on my 60hz screen don't work well.
Anyway, try to use the latest Anime4K shader v3.0 with the "UL" variant. I get 2 fps with my GTX 1060 hahaha, I think it require a 2080.  The default option suggested by the author works like a charm instead. 3.0 it's better than v2.1aL.

**Comment by bloc97** [comment]
> I get 2 fps with my GTX 1060
Is it for 1080p or 480p videos? The UL version is overkill for 1080p videos since they almost contain no small detail.
Also, it must be due to cache issues or something like that, since the UL version should be only (in theory) 5x slower than the L version. (5x more multiply-add operations)

**Comment by bloc97** [comment]
I will do some tests on lower end GPUs and get back to you. I think that a 1060 should be powerful enough to run one pass of the UL upscaler variant without problems.

**Comment by chrnodroid** [comment]
> Is it for 1080p or 480p videos? The UL version is overkill for 1080p videos since they almost contain no small detail.

Is it for 480p videos,  2fps on my 1060.
While the L variant is 23fps, it's good. This is strange.

I'm using only these two lines:

This for 480p videos  (2 fps), here there is something wrong. 
`CTRL+1 change-list glsl-shaders set "~~/shaders/Anime4K_3.0_Upscale_CNN_UL_x2_Denoise.glsl;~~/shaders/Anime4K_3.0_Auto_Downscale_Pre_x4.glsl;~~/shaders/Anime4K_3.0_Deblur_DoG.glsl;~~/shaders/Anime4K_3.0_DarkLines_HQ.glsl;~~/shaders/Anime4K_3.0_ThinLines_HQ.glsl;~~/shaders/Anime4K_3.0_Upscale_CNN_UL_x2_Deblur.glsl"`

And this for 1080p videos (23fps) 
`CTRL+2 change-list glsl-shaders set "~~/shaders/Anime4K_3.0_Denoise_Bilateral_Mode.glsl;~~/shaders/Anime4K_3.0_Deblur_DoG.glsl;~~/shaders/Anime4K_3.0_DarkLines_HQ.glsl;~~/shaders/Anime4K_3.0_ThinLines_HQ.glsl;~~/shaders/Anime4K_3.0_Upscale_CNN_UL_x2_Deblur.glsl"
`

**Comment by mhtvsSFrpHdE** [comment]
> 
> 
> @chrnodroid @lux-perpetua @bloc97
> I'm not using any kind of SVP-like smooth plugin, but that reminds me!
> I then just checked my `mpv.conf`, and noticed something like:
> 
> ```
> # Interpolation
> video-sync=display-resample
> tscale=oversample
> ```
> 
> Well I didn't realize that would be a heavy performance option...
> I was thought it is "non-integer frame interval conversion",
> when I use other media player this feature is almost zero-performance hit.
> 
> After comment the two lines out, everything is fine and I got 0 frames drop!
> Thank you!

The correct tool that I actually need is not interpolation, is "video-sync".  
Just remove all interpolation related entry and set `video-sync=display-resample`.  
This is the equipment to zero-cost frame interval conversion in MPV.

**Comment by mhtvsSFrpHdE** [comment]
@chrnodroid Thanks! But I need is just simple `video-sync=display-resample`,  
that's enough for me. I'm not looking for smooth video, just frame interval conversion.
