### ISSUE TITLE
Add note about unix separator to instructions.

### ISSUE THREAD

**Issue by iwalton3** [bloc97/Anime4K#83]
The MPV `input.conf` settings in the [usage instructions](https://github.com/bloc97/Anime4K/blob/master/GLSL_Instructions_3.0.md) do not work on Linux by default.

To fix this, add a note for Linux users telling them to replace the `;` with `:` in the `input.conf` to the instructions.

**Comment by bloc97** [comment]
Thanks for the notice, I've just added it in the usage instructions.
