### ISSUE TITLE
[Q] Is there a way to buffer the shaders on mpv so that we can use them on slower machines?

### ISSUE THREAD

**Issue by NightMachinary** [bloc97/Anime4K#86]
My 2016 Macbook Pro can't handle the shaders in realtime, but I think allowing it to build a buffer of like 5 minutes should make a realtime play of anime episodes possible.

**Comment by ThoughtfulDev** [comment]
Have you tried using less shaders and using the smallest shader version? (uses about 500mb vram on my machine).

**Comment by NightMachinary** [comment]
@ThoughtfulDev You're right, that works, too. Using Anime4KCPP also works.
