### ISSUE TITLE
Denoise-Bilateral Variants

### ISSUE THREAD

**Issue by ThoughtfulDev** [bloc97/Anime4K#87]
Hey,
since its not mentioned in the latest commit. Whats the reasons for the different Denoise-Bilateral Variants?

Do you have already found a use case for the different methods? e.g one works well with dark scenes etc?

**Comment by bloc97** [comment]
The bilateral mode filter can introduce severe aliasing if set too high. The bilateral mean introduces a lot of blur if set too high but has no aliasing issues. The bilateral median is a good compromise between the two but is much slower. (The median is the hardest central tendency to find of the three.)

If your scene is always dark you can try to set the `INTENSITY_POWER_CURVE` to 0. It is not 0 by default since lines in anime are mostly always black and it causes too much smoothing.

**Comment by Jules-A** [comment]
[Here's a difference](https://cdn.knightlab.com/libs/juxtapose/latest/embed/index.html?uid=58187158-9215-11ea-a879-0edaf8f81e27) between Median and Mode with Upscale_CNN_M_x2_Deblur and Thin/Dark lines (all default settings except line intensity slightly reduced).

Although, Median is much heavier so it's probably fairer to compare against [Mode + L deblur](https://cdn.knightlab.com/libs/juxtapose/latest/embed/index.html?uid=a645c6a4-9216-11ea-a879-0edaf8f81e27).

Both comparisons median is on left.

Here's what [no shaders and MadVR looks like](https://cdn.knightlab.com/libs/juxtapose/latest/embed/index.html?uid=8165ce78-9217-11ea-a879-0edaf8f81e27).

Source: Funimation(Tokyo Majin) - 480p so easier to compare but it's still 8.1MB/s...

**Comment by ThoughtfulDev** [comment]
Thank you both @bloc97 and @Jules-A  for the comparison!
So if speed isn't an issue (or hardware) Median is the way to go i assume. 

I am trying to figure out the best settings for a variety of anime. Kind of like profiles of shaders for different kind of anime.

**Comment by Jules-A** [comment]
> Thank you both @bloc97 and @Jules-A for the comparison!
> So if speed isn't an issue (or hardware) Median is the way to go i assume.

If speed isn't an issue then I think you are better with the Anime4K_3.0_Upscale_CNN_L_x2_Denoise variants but it's too heavy (even the M) for my system so I haven't done any real detailed comparisons. It runs fine for 480p anime but struggles on anything higher.

**Comment by ThoughtfulDev** [comment]
Oh yeah sure. I was just curious about the Denoise Bi. Since i upscale from 1080 to 4K (with my python wrapper which i may publish soon). I always use the XL variants (ryzen 3600, gtx 1060) to encode the file (i dont do live watching). I think in encoding its not so much an issue since you dont have to watch it at the same time. The only issue when encoding is RAM and VRAM. I have run into cases where are Movie Remux upscale to 4K got killed by the OOM Killer of Linux before i ran out of 16GB RAM.
