### ISSUE TITLE
"Further details about each shader and its purpose will be released soon."

### ISSUE THREAD

**Issue by xXHenlolXx** [bloc97/Anime4K#90]
I know that you are probably busy with other things. But I'm still waiting for details on v3.0 to use it. It's just that it looks like you forgot. Anyway, thanks for your shader, I love it!

**Comment by bloc97** [comment]
I haven't forgot. Here's my first attempt at explaining all the shaders.
https://github.com/bloc97/Anime4K/wiki
I hope it is helpful!

**Comment by xXHenlolXx** [comment]
Thanks! I didn't know. And congratulations on your partnership with Crunchyroll.

**Comment by bloc97** [comment]
I'm not aware of any partnership with Crunchyroll. Do you have a link?

**Comment by xXHenlolXx** [comment]
https://medium.com/crunchyroll/scaling-up-anime-with-machine-learning-and-smart-real-time-algorithms-2fb706ec56c0 They are using your shader to upscale

**Comment by bloc97** [comment]
Yea, I just found that in their blog. However they are using the outdated v0.9? v1.0? shader. I wonder if they would be willing to implement the newer version as it is higher quality.
