### ISSUE TITLE
Anime4K cost much GPU usage on MacOS...

### ISSUE THREAD

**Issue by gth7754125** [bloc97/Anime4K#96]
**Describe the bug**
When i use Anime4K to scale up a 1080p Anime, it makes my GPU increase about 15% usage, sometimes about 20%.  i don't know wheter the case is normal, or just my macbook's display card too suck..

Here is my mpv config.
```
macos-force-dedicated-gpu=yes
profile=gpu-hq
glsl-shaders-clr
# Anime4k-1080p-Improve perceptual quality
glsl-shaders="~~/shaders/Anime4K_Denoise_Bilateral_Mode.glsl:~~/shaders/Anime4K_DarkLines_HQ.glsl:~~/shaders/Anime4K_ThinLines_HQ.glsl:~~/shaders/Anime4K_Upscale_CNN_M_x2_Deblur.glsl"
# scale=spline36
dscale=mitchell
cscale=mitchell
```

**Screenshots**
![Snipaste_2020-07-05_18-13-44.png](https://i.loli.net/2020/07/05/ge2VKz7MqIhUS3c.png)
![Snipaste_2020-07-05_18-14-40.png](https://i.loli.net/2020/07/05/gPGICV1fhXK2jct.png)

**Desktop (please complete the following information):**
- Machine: Macbook Pro 2017 (screen resolution :2880 x 1800)
 - OS: MacOS Catalina 10.15.5
 - GPU: Radeon Pro 555
 - Media Player : MPV 0.32
- External Shader： Anime4K - 1080P-Improve perceptual quality setting

**Comment by Artins90** [comment]
I think that's normal.  
It uses roughly 20% GPU usage on my RTX 2080 TI running on Windows, albeit at 1.35 Ghz rather than the full 2 Ghz the GPU can reach.
This is with the Large version of the shaders.

**Comment by gth7754125** [comment]
em...Can i just change DarkLines/ThinLines **HQ**  to their **Fast** version or **Very Fast** ?
Will it highly affect the quality of 1080P or 4K content ?

**Comment by Artins90** [comment]
All the shaders come with different quality/performance versions.
As you can see here, the Medium version of the upscale shader is roughly 60% lighter than the Large version (1.5ms vs 2.6ms): https://raw.githubusercontent.com/bloc97/Anime4K/master/results/Comparisons/Bird/Compare.png
