### ISSUE TITLE
The current experimental denoiser "Heavy" seems to kill details

### ISSUE THREAD

**Issue by Artins90** [bloc97/Anime4K#97]
Probably it's not meant to be used on videos with good compression but so far it's not looking great.
Some of the lines nearly disappear (inside the ear, hairpin like accessory) and there is a general loss of detail:  
No shaders active: https://i.imgur.com/obbxJ9a.jpg
New denoiser + darklines hq + thinlines hq + upscaleM x2 Deblur: https://i.imgur.com/xGXlde0.jpg

**Comment by Jules-A** [comment]
I already commented about this here: https://github.com/bloc97/Anime4K/commit/d2193a5a73e3ddacee03fe9e05e7508dd9fa42ea#commitcomment-40893355 which has a response from the author.
